function fun() {
  down.innerHTML = arr[Math.floor(Math.random() * arr.length)];
}
var down = document.getElementById("demo");
var arr = [
  "लक्ष्य को प्राप्त करने का सबसे आसान तरीका निरंतर प्रयास करना हैं",
  "एक दिन फिर निकल जाऊंगा देख लूंगा क्या है उसे पहाड़ के पार",
  "तुमको कभी लगे तुम थक चुके हो तो एक बार अपने पापा को देखना",
  "जो कुछ भी अपने देर से सीखा है उसे अपने बच्चों को जल्दी सिखाएं",
  "Be patience sometimes the weight is longer because the blessing is bigger",
  "अगर कोहिनूर से भी कोई कीमती है तो वह है मेरे मां-बाप",
  "सब्र कभी मत खोना क्योंकि हर बड़ी कामयाबी वक्त मांगती है",
  "शर्म और डर आपको काम और फैसला दोनों नहीं करने देगा",
  "जब रब के फैसलों पर यकीन होने लगे तब दिल जिद करना छोड़ देता है",
  "ज्यादा देने वाला हमेशा से थक गया है चाहे फिर वह प्रेम हो साथ हो समय हो या विश्वास",
  "थोड़ा और समझदार होने के लिए थोड़ा और अकेला होना पड़ेगा",
  "पिताजी के जैसा बनने का बचपन में बड़ा शौक था लेकिन यह नहीं पता था कि ईश्वर की बराबरी संभव नहीं है",
  "Accept the situation and say...... चलो यह भी ठीक है",
  "Silence is the best answer for all questions smiling is the best reaction in all situations",
  "मर्द की इज्जत वही औरत कर सकती है जिसने अपने घर पर अपने आप की इज्जत होती देखी हो",
  "दुखी हो भगवान से बात करो खुश हो भगवान की स्तुति करो समस्या है भगवान से मांगो उदास हो भगवान के सामने रो लो",
  "जो भगवान की शरण में आता है उसका अतीत चाहे जैसा भी हो वह शीघ्र ही शुद्ध होकर महात्मा बन जाता है भक्ति हर पाप का नाश कर देती है",
  "नाम जपने पर मन में बेकार आना अंतःकरण शुद्ध होने का संकेत है",
  "Nazar is real protect your happiness",
  "मां के चक्कर में फंसे तो माया में उलझ जाओगे",
  "क्रोध करके वह सब मत गवाए जो आपने शांत रहकर कमाया है",
  "हंसकर कोने में और खोकर हंसने में हिम्मत चाहिए",
  "रिश्तो को कभी धोखा मत दीजिए पसंद ना आए तो पूर्ण विराम दीजिए",
  "भक्ति क्या है उच्चतर आत्म के प्रति मोहन प्रेम जितना अधिक शांत होता है जितना ज्यादा शक्तिशाली और शुद्ध होता है उतना ही ज्यादा",
  "पैसा तभी आएगा जब आप पैसा के बारे में सोचोगे",
  "थोड़ी शांति दो मन को बस हो गया बहुत हो गया थोड़ी शांति लो",
  "प्रेम जिससे किया जाता है उसका सम्मान प्रेम से ज्यादा किया जाता है",
  "We broke our rules The Bill comes due",
  "Don't forget You are living someone's Dream life Isn't it??",
  "बेच दूं क्या सारी परेशानियां....मौत अच्छा दाम दे रही है,,,!!!",
  "अपनो ने ही सिखाया है की अपना कोई नही होता !",
  "सबकुछ हासिल हो जाए पल भर में, गलती से भी गलत गलतफ़हमी मत पालिए..!!",
  "अकेलापन एक संकेत है कि परमात्मा तुम्हें अपनी ओर चलाना चाहते हैं।",
  "NO ONE CARES UNTIL YOU'RE RICH, FAMOUS OR DEAD.",
  "Never Judge The Future Of A Person Based On Their Present Situation, Because Time Has The Power To Turn Any Black Coal Into Diamond.",
  "कर्म बदलिये, किस्मत वो खुद बदल देंगे",
  "घर से निकल कर वापिस सुरक्षित घर लौटना भगवान का एक ऐसा आशीर्वाद हैं जिसे लोग आँकते ही नही है..100",
  "संस्कार दिए बिना सुविधाएँ देना पतन का कारण है। बच्चे को सुविधाएँ न दो तो थोड़ी देर रोयेगा लेकिन संस्कार न दो तो पूरी ज़िन्दगी रोना पड़ेगा। भीष्म पितामह लोक पंक्तियाँ",
  "संघर्ष में तुम अनाथ हो मित्र, काफिला तो सफ़लता के बाद उमड़ता है?",
  "कुछ लोग जिधर की हवा है उधर चल पड़ते हैं, हालांकि ये काम कचरे का होता है..",
  "अकेले खड़े रहने का साहस रखो, दुनियाँ ज्ञान देती है साथ नही.. 100",
  "नींद, नशा और नारी 100% बर्बादी की सवारी..!!",
  "कोई व्यक्ति कितना भी खास क्यूं ना हो, उसे एक पल में त्यागने की क्षमता तुममें अवश्य होनी",
  "हम बोलते भी कुछ नहीं और भूलते भी कुछ नहीं.. ",
  "ख़ास होने का भ्रम ना पाले, आपको पाकर लोग आपसे बेहतर की तलाश में रहते है.. ",
  "power agar dusre ke naam se huai to vo power apni thoda na hui ve compunder",
  "gupta postman hai or postman ki maari nahi jaati varna next chitti vahi fad dega",
  "Jo pahle nahin kar sakte the vah ab kar sakte hain to kahe nahin Karen",
  "Jo pahle nahin kar sakte the vah ab kar sakte hain to kahe nahin Karen Isi ka Naam tarkki hai",
  "Family family Hoti hai family chai kaisi bhi ho family ke sath khada rahana padta hai",
  "Janata ka safe hona jaruri nahin hai safe dekhna jaruri hai",
  "Sarson Ko jitna mishenge utna hi tel nikalega",
  "Chutiya hai yah important nahin hai hamara ladka hai yah important hai",
  "Yah to power tumhare pass hai na iske liye tumhen kuchh karna nahin pada yah tumko बैठे-बैठे Mili hai power jo hai na netaon ki tarah hoti hai रातों-रात party Badal leti hai",
  "Vah kya hai hamara manana hai ki Vyapar mein partnership jabardasti nahin ki jaati  Partner bol diya aapane bahut ijjat diye bhai",
  "Ham bhi loyal the tum bhi loyal Ho ham bhi Pi le Gaye Tum bhi Pi le jaaoge",
  "Matter internal hai internali sulat jaega saamp ko Kitna bhi dudh pila Lo rahata to vah jahreela hi hai na",
  "Ham jante hai tum unke baap ho But tum unke Dushman mat Bano",
  "Family ki Rai se chaloge to family ko aur bhi proud karaoge",
  "Aadami ka Darna jaruri hai marna nahin",
  "Kutte ke Malik ko dost banaa lo vah apne aap mokna band kar dega",
  "Kuchh log Bahubali paida hote hain kuchh ko banana padta hai",
  "Kya sikhe Munna  Yahi ki jab bali Dene ka time aaye to bali sipahi ki di jaati hai  Raja or rajkumar hamesha raj karte hai",
  "Babuji Babu Bahubali hone mein sirf power hai Samman to rajniti nahin milta hai Rajniti ka Samman kursi se juda hota hai kursi Kai Samman hai Power Raja mein nahin use banane Wale mein hun Bus nirnay Apne hath mein rakho",
  "Men baat yah hai ki log start hi nahin karte kam se kam start to kar sab hoga jyadatar log start hi nahin karte bus tu kar kuchh bhi kar bus shuru kar pahle kyunki Jo tu Karega usse kuchh Na kuchh sikhane ko jarur milega Jin logon ne start kiya hai unhone bahut kuchh ukhada hai to jinhone nahin kiya hai vah rah Gaye piche isliye tu bhi kar",
  "Choose happiness now resistance block your desire from coming to you . you created resistance in yourself by feeling anxious or worried about receiving what you want.  You will melt away those negative feelings that are causing resistance and blocking delivery when you find a way happy now before receiving your desire",
  "Proclaim it to create it. To speed up any manifestination think talk and write about your desire in the present tense only I have all the money that I need there is no past or future for the law of attraction if you proclaim it as existing new the universe must get very busy very quickly",
  "What you resist persist That means whatever you passionately don't want you are inviting to you put the power of your passionate emotions into what you do want and bring those things to you",
  "Jab kuch bhi na karna ka man kare tab bas Ram ram ram ram ram ram ram ram ram ram ram ram ram ram ram ram ram ram ram ram ram ram ram ram ram ram ram ram ram ram ram ram ram ram ram ram ram",
  "मानो तो मौज है वरना समस्याएं तो हर रोज है",
  "संकट का समय आने से पहले ही जो समझ जाता है उनके जीवन में संकट ही नहीं आता है और उनका समय स्वर्णिम हो जाता है",
  "दिखाना कुछ करना कुछ",
  "Let’s team up! I’ll build the product, and you’ll handle the marketing. — Indie Hacker",
  "कीचड़ में पैर फंस जाये तो नल के पास जाना चाहिए, मगर नल को देखकर कीचड़ में नही जाना चाहिए इसी प्रकार..जिन्दगी में बुरा समय आ जाये तो पैसों का उपयोग करना चाहिए, मगर पैसों को देखकर बुरे रास्ते पर नही जाना चाहिए.",
  "That one boring friend who is serious about his future You are not always going to be motivated but you have to disciplined",
  "मैं वह खिलाड़ी हूं जो हारे हुए गेम को भी जीतने का हुनर रखता हूं",
  "Never hearty person who silent maybe he is waiting for the right time",
  "Big dream stay silent keep them to yourself let the results speak loud while others wonder how you did it",
  "Bekhabarli have one Amla Delhi limit sugar in take drink 3l of barm water Learn a new skill retain page Delhi's sleep 728 hours 30 minute bricks walk meditate",
  "Wearing black can make you seeing more dominant powerful and mysterious red fools people nervous system and make your seem more dangerous",
  "People think this is the hotness but multi millionaire think this is real hot car Lamborghini",
  "Maybe your heart is like a stone I mean unbreviable unbreakable but one fake smile is enough to destroy you so only focus on your goals not a few smile",
  "Never cry 4 the person who hurts you just smile and say thanks for giving me the chance to find someone better than you",
  "You lost focus again take back your control",
  "Feminine depression last fat and laziness weakness no get strong get rich get discipline become man",
  "My grades are better than yours",
  "khichadi me jo marji dalte jaye vo rahegi khichadi",
  "समय हो जाए तब समय से जग जाने में ही सयानापन है अच्छा और सच्चा समय बीत जाने के बाद कितना भी समय मिले सब बेकार है",
  "एक बात याद रखना कि लोग आपके बारे में सुनी हुई अच्छी बातों को आपसे दोबारा पूछने आएंगे लेकिन बुरी बातों पर बिना पूछे विस्वास कर लेंगे",
  "अच्छे जरूर बने लेकिन साबित करने की कोशिस ना करे",
  "ये अलग बात है कि सुनी तेरी गई वरना खुदा तो मेरा भी है",
  "Efforts Matter Not promises..",
  "बहुत गुरूर था 'छत' को 'छँत' होने का, एक मंज़िल और बनी 'छत' फर्श हो गई।",
  "अगर तुम्हारे ख्वाब बड़े है, तो संघर्ष कैसे छोटा हो सकता है।",
  "खुद पर विश्वास रखा करो फिर देखना एक दिन ऐसा आएगा कि घड़ी दूसरो की होगी पर समय आपका होगा।",
  "No rest is worth anything except the rest that is earned",
  "kis time par apna talant dikhate ho ye matter karta hai",
  "bijnesh me akela insan sirf ek paani ki bund ke saman hai or puri team ek samudra ke saman lhia",
  "agara tumhe kahi jaldi pahuchna hai to akele jao or agar dur pahuchana to ek saath jao",
  "agar aap kisi chiz ko dhang se naap nahi sakte to use kaat bhi nahi sakte isliy darzi ko do baar napna chahiye ",
  "Anything that can't be measured, can't be improved",
  "gussa mat karo gusse ko positive lo kyoki raste me jitni rukavete aayengi utne hi majboot hoyoge tum",
  "jitna bada villon aayega utna bade hero banegoge",
  "insan ho to galti hogi lekin apni galti ko swikar karke unke sudharo",
  "kathin paristihi aa rahi hai to parishram kro succes jarur milegi ",
  "apni weakness par ek list banaiye or us par kaam kijiye",
  "selfstudy",
  "Love can leave a memory that no one can steal, but can also leave a pain that no one can heal.",
  "An idiot with a plan can beat a genius without a plan.",
  "100 saal zinda rahne ke liye 100 saal jine ki jarurat nahi hai",
  "Kuch aisa kaam karo ki log tumhe 100 saal yaad rakhe",
  "THOSE WHO NEVER START, NEVER SUCCEED",
  "दिल सागर जैसा रखना चाहिए, नदियाँ खुद ब खुद मिलने आएँगी",
  "  खुदा सलामत रखे गाना आंखों को जिनमें आजकल हम चुभते हैं",
  "कोई इंसान मिले तो बताना हम खुद आएंगे उसे सलाम करने",
  "तावहियो का दौर है जनाब शांति की उम्मीद हमसे ना लगे",
  "क्या यकीन करना गैरो पर चलना है खुद के पैरों पर",
  "मेहनत आदत बन जाए तो कामयाबी मुकद्दर बन जाती है",

  "इस दुनिया में कोई किसी का हमदर्द नहीं होता, लाश को शमशान में रखकर अपने ही लोग पूछते हैं कि कितना और वक्त लगेगा।",
  "या तो तू मेरे पास आजा या मुझे बुला ले। अब तन्हा रहा नहीं जाता तू मेरे नाल ब्याह रचा ले।।",
  "अब उनसे बात नहीं होती मेरी जिन्हें अपनी हर बात बता चुका हूँ में",
  "मुझसे नफरत तभी करना जब आप मेरे बारे में सब कुछ जानते हो, तब नहीं जब किसी से मेरे बारे",
  "कैसे करूँ मैं साबित...कि तुम याद बहुत आते हो, एहसास तुम समझते नही और अदाएँ हमे आती नहीं...",
  "जहाँ चार लोगों में बैठकर आप किसी की हँस-हँसके बुराई करते हो, यकीन मानिए वहाँ से जाते ही आपकी बुराई शुरू हो जाती है।",
  "अपने आप को मत सुनो, उस सलाह को सुनें जो आप दूसरों को देते हैं।",
  "घर के अंदर जी भर के रो लो, पर दरवाजा हंसकर ही खोलो क्योंकि लोगों को यदि पता लग गया कि तुम अंदर से टूट चुके हो, तो वह तुम्हें लूट लेंगे..",


  "बेज्जती का जवाब इतने इज्जत के साथ दीजिए कि सामने वाला भी शर्मिंदा हो जाए.",
  "इंसान खुद की नज़र में सही होना चाहिए.. दुनिया तो भगवान से भी दुखी हैं..",
  "इंसान धर्म, जाति, गोत्र, कुण्डली ओर सैलेरी देखने के बाद कहता है कि.. जोड़ियां तो ऊपर वाला ही बनाता है ..",
  "प्यार करना गलत नहीं है, लेकिन कैरियर छोड़ कर प्यार करना बहुत बड़ी मूर्खता है।",
  "अंधेटे से मत डटो सितारे अंधेरे में ही चमकते हैं",
  "जमाना क्या कहेगा ये मत सोचो ! क्योंकि जमाना बहुत अजीब है, ये नाकामयाब लोगों का मजाक उड़ाता है, और कामयाब लोगों से जलता है !",
  "एक इच्छा कुछ नही बदलती एक निर्णय कुछ नही बदलता लेकिन एक निश्चय सब कुछ बदल देता हैं, a Helo",
  "दुनिया मे आये हो तो कुछ करके जाओ वरना ज़िन्दगी तो जानवर भी काट लेते है.",
  "शिकवे तो सबको हैं इस ज़िन्दगी से, मगर जो मौज से जीना जानते हैं वो शिकायत नहीं करते।",
  "कोई जोखिम ना लेना ही जीवन का सबसे बड़ा जोखिम हैं",
  "कर्म करो तो फल मिलता है, आज नहीं तो कल मिलता है जितना गहरा हो कुआँ, उतना मीठा जल मिलता है",
  "रुलाया ना कर हर बात पर ऐ जिंदगी.... जरूरी नहीं है.. सबकी किस्मत में चुप कराने वाला हो...",
  "कुछ लोगों में ये क़ाबिलियत होती है, आप कितनी भी अच्छी बात कहें, वो उसमें बुराई ढूँढ ही लेते हैं.. आप अपना ध्यान रखें।",
  "दुआओं के सामने सब फेल। उसे कमाना आपके हाथ में।",
  "कोई कुछ भी बोले अपने आप को शांत रखो, क्योंकि धूप कितनी भी तेज हो समुन्द्र सूखा नहीं करते।",
  "मुस्कुरा कर दर्द को सहना क्या सीख लिया सबने सोच लिया हमे तकलीफ ही नही होती.!",
  "हालातों पर इतना ध्यान मत दो कि सपनों को ही भूल जाओ बल्कि अपने सपनों पर इतना ध्यान दो कि हालात याद ही ना रहें।",
  "अभिमान नहीं होना चाहिए कि मुझे किसी की जरूरत नहीं पडेगी और यह वहम भी नहीं होना चाहिए कि सबको मेरी जरूरत पड़ेगी...",
  "Apni acchai par kya guroor karu, Kisiki kahani mein shayad mein bhi galat hoon.",
  "जिन्दगी जीना आसान नहीं होता, बिना संघर्ष के कोई महान नहीं होता, जब तक ना पड़े हथोड़े की चोट, पत्थर भी भगवान नहीं होता!!",
  "शर्म आती है ऐसे पढ़े लिखो पर एक सीट अपने STRUGGLE को तब तक SECRET रखिये, जब तक आप सफल नहीं हो जाते!",
  "तू कभी जो रूठ गई तरकीब बता देना मनाने की मैं जिंदगी गिरवी रख दूंगा तबस कीमत बता देना",
  "कोई आपको बुरा कहे तो केहने दो क्योंकि, आदमी अच्छा था ये सुनने के लिए मरना पड़ता है !",
  "अदृश्य वायरस यदि आपको डरा सकता है तो अदृश्य भगवान आपको बचा भी सकता",
  "HACKING IS NOT A COURSE IT'S A SKILL THAT YOU HAVE TO DEVELOP IN YOURSELF",
  "मिजाज जिनके अलग होते हैं ना जनाब चर्चे भी उन्हीं के होते हैं",
  "Kisi ladki ko itna bhi massage mat karo ki vah khud ko katrina or tumko kameena samjhne",
  "हिम्मत इतनी बड़ी रखो कि किस्मत छोटी लगने लगे",
  "गद्दार दोस्त सच्चा दुश्मन हमेशा अच्छी सीख देते हैं",
  "लोग हैसियत पूछ रहे थे मैंने अपने दोस्तों के नाम बता दिए",
  "जिसको अपना समझा था वही मुझे दगा दे गए",
  "काम निकलते ही अपनों को बदलते देखा है मैंने",
  "शक करना बिल्कुल गलत था लेकिन सब सही था",
  "जो बदलता है वह आगे बढ़ता है",
  "राज कुछ दफन कर रखी है मैंने किरदार कुछ लोगों के सलामत है इसी तरह",
  "ऐसे जियो जैसे कल मरने वाले हो ऐसे सीखो जैसे हमेशा जीने वाले हो",
  "सिर्फ सुनो मत सोना भी दो और हद पार कर दो उड़ा भी दो",
  "जीवन में एक दूसरे को समझने का प्रयास करो परखने का नहीं",
  "अपने ही हमें खुश नहीं देखना चाहते गैरों से क्या शिकायत",
  "जिस दिन मुझे खो दोगे मुस्कुराते हुए भी रोते हुए",
  "जब लोग बदल सकते हैं तो किस्मत क्या चीज है",
  "समय ना लगाओ तय करने में कि आपको क्या करना है वरना समय तय कर लेगा कि आपका क्या करना है",
  "कोई किसी का नहीं होता जनाब सब मतलब के साथी हैं",
  "मैदान तब तक मत छोड़ना जब तक तुम जीत नहीं जाते",
  "मतलब की दुनिया है जनाब काम होते ही औकात भूल जाते हैं",
  "बुरा वक्त भी कमाल का होता है जी जी कहने वाला भी तू तू कहने लगता है",
  "हमेशा खास बनो आम बनोगे तो दुनिया आचार डाल लेगी तुम्हारा",
  "माना कि अच्छे लोगों के साथ बुरा होता है यह भी सत्य है लेकिन बुरे लोगों के साथ भी बुरा होता है यह भी सच है",
  "आज मुझे अकेला समझकर मत सता कल कयामत के दिन में खुदा को साथ लेकर आऊंगा",
  "गलत डिसीजन ना लेने से जितने failurs नहीं आए हैं बल्कि डिसीजन ना लेने से failurs आते हैं",
  "तुम कभी नहीं जीतोगे अगर तुम शुरुआती नहीं करोगे",
  "Ek baap ke ho to ek aurat ke hona seekho",
  "Kaha milta hai koi samjhne vala Jo bhi milta hai samjha ke chala jata hai",
  "अगर दुनिया तुम्हारी क्षमता पर संदेह करे तो दुखी मत होना क्योंकि सोने कि शुद्धता पर ही संदेह किया जाता हैं",
  "Mere baare me kuch bura bolna to direct mujhse bolna q ki mere koi branch nahi hai",
  "किसी के इतने करीब मत जाओ कि उसे तुम्हारी  अच्छी लगने लगे",
  "कुछ पत्थर कोशिशों के लिए मारे जाते हैं हर पत्थर से फल थोड़ी टूटते है",
  "इंसान एक दुकान है, और ज़ुबान उसका ताला, ताला खुलता है, तभी मालूम चलता है कि दुकान सोने की है या कोयले की",
  "पहचान बड़े लोगों से नहीं समय पर साथ देने वालों से होनी चाहिए",
  "‘मन में उतरना’ और ‘मन से उतरना’ केवल आपके व्यवहार पर निर्भर करता है..!",
  "होने वाले खुद ही ‘अपने’ हो जाते हैं, किसी को कहकर ‘अपना’ बनाया नहीं जाता",
  "मुसीबत में फंस जाने पर मनुष्य को गृह दोष , वास्तु दोष , पितृ दोष , शनि दोष कालसर्प दोष सब दिखाई देने लगते हैं, केवल खुद का दोष दिखाई नहीं देता मोह में हम बुराइयां नहीं देख पाते और घृणा में हम अच्छाइयां नहीं देख‌ पाते",
  "इंसान जन्म के 2 वर्ष बाद बोलना सीख जाता है। लेकिन बोलना क्या है, यह सीखने में पूरा जन्म लग जाता है।",
  "किरण चाहे सूर्य की हो या आशा की जीवन के सारे अन्धकार मिटा देती है",
  "मन के जिस दरवाजे से 'शक' अन्दर प्रवेश करता है, 'प्यार' और 'विश्वास' उसी दरवाजे से बाहर निकल जाते हैं",
  "पंछी कभी भी अपने बच्चों के भविष्य के लिए घोंसला बनाकर नहीं देते, वे तो बस उन्हें उड़ने की कला सिखाते हैं",
  "आपकी कीमत इसमें है कि आप क्या हैं, इसमें नहीं कि आपके पास क्या है",
  "दिल से फैसला करो तुम्हें क्या करना है, दिमाग अपने आप तरकीब निकाल लेगा",
  "मनुष्य के लिए बुरी संगत उस कोयले के समान है, जो गर्म हो तो हाथ जला देता है और ठंडा हो तो हाथ काले कर देता है...",
  "दो ही चीजें ऐसी हैं जिन्हें देने से किसी का कुछ नहीं जाता, एक मुस्कुराहट और दूसरी दुआ, इन्हें जितना बाटेंगे, उतनी ही ज़्यादा आपको मिलेंगी",
  "किसी का सरल स्वभाव उसकी कमज़ोरी नहीं... बल्कि उसके मां बाप के के दिए हुए संस्कार होते हैं",
  "कमाल का ताना दिया, आज मंदिर में भगवान ने- मांगने ही आते हो, कभी मिलने भी आया करो",
  "जो‌ चाहा वो मिल जाना सफलता है, जो मिला, उसे चाहना प्रसन्नता है",
  "वक़्त वही है, चाहो तो सोना बना लो, चाहो तो सोने में गुजार दो",
  "अंदाजा 'ताकत' का लगाया जा सकता है, 'हौसलों' का नहीं",
  "प्यार में ही ताक़त है दुनिया को झुकाने की वरना क्या जरूरत थी रामजी को जूठे बेर खाने की",
  "ज़िन्दगी में जब बचपन के खेल ख़त्म हो जाते हैं उसके बाद फिर किस्मत के खेल शुरू होते हैं..",
  "कभी मायूस मत होना दोस्तों, ज़िन्दगी अचानक कहीं से भी अच्छा मोड़ ले सकती है",
  "जरूरी ये नहीं कि आपकी उम्र क्या है, जरूरी ये है, कि आप किस उम्र की सोच रखते हो",
  "खून के रिश्ते तब तक साथ में रहते हैं जब तक प्रॉपर्टी बीच में ना आवे",
  "जब आप ऊँचाइयों की सीढ़ियाँ चढ़ रहे हों तो पीछे छूटे लोगों से बहुत अच्छा व्यवहार करें, क्योंकि उतरते समय वही लोग आपको रास्ते में फिर मिलेंगे",
  "भगवान से भी बड़े माता पिता होते हैं, क्योंकि भगवान सुख दुःख दोनों देते हैं परंतु माता पिता सिर्फ़ सुख देते हैं",
  "आज से बेहतर कुछ भी नहीं, क्योंकि कल कभी आता नहीं और आज कभी जाता नहीं",
  "जब आपके एक से अधिक दुश्मन हो तो वहां पर शारीरिक रूप से नहीं दिमागी तरीके से लड़ाई लड़ें",
  "अगर आप ज़िद्दी हो तो  आप अपने हर सपने को हकीकत में बदल सकते हो",
  "दुनिया का सबसे फायदेमंद सौदा बुजुर्गो के साथ बैठने में है चंद लम्हों के बदले मे वो अपना वर्षो का तजुर्बा से देते है",
  "इज़्ज़त तो सबको ही चाहिए लेकिन लोग वापस देना भूल जाते है भगवान से कुछ माँगना ही है, तो हमेशा अपनी माँ के सपने पूरे होने की दुआ माँगना, तुम ख़ुद ब ख़ुद आसमान की ऊँचाइयाँ छू लोगे आवाज़ नहीं .. बात ऊँची होनी चाहिए।",
  "किसी की फिक्र करना अच्छी बात है लेकिन खुद की फिक्र करना कमाल की बात है",
  "कोई काफ़ी अकेला है, और कोई अकेला ही काफ़ी है",
  "अपने बुरे समय में भगवान और समय दोनों पर विश्वास रखें, क्योंकि समय कोयले को भी हीरा बना देता है और भगवान रंक  को भी राजा",
  "जो अच्छा लगे उसे ग्रहण करो, और जो बुरा लगे उसका त्याग ..फिर चाहे वह विचार हो, कर्म हो, या मनुष्य",
  "Apne field me master ban jao",
  "Utho jago or laksh prapti tak mat ruko",
  "Ias so har saal nikalte hai Lekin billgetes sadiyo me ek baar nikalta hai",
  "Rukawat to zinda Insan ko hi aati hai Murdo ko nahi",
  "जब आप कुछ नहीं कर सकते तो एक चीज जरूर करे प्रयास",
  "हर बेटी अपने पापा के लिए परी होती हैं",
  "If you're not paying for the product, then you are the product.",
  "Nothing vast enters the life of mortals without a curse.",
  "Disappear from where you are not valued",
  "You love them more when they're not okay. Love yourself exactly like that.",
  "apni weakness se dariye nahi us par kaam kijiye",
  "mansikta thik hogi to vastivikta bhi thik hogi",
  "apne aap ko express karo jo bhi activity ki use express karo ",
  "jab jo bhi task kar rahe ho usme ji jaan lagado continuti",
  "those who focus on making a sale, neither get sale nor get costuomer",
  "munafe ko chunane ki bajay agar grahak ko sunane par dhyan doge to bijnes me hamesh sabse aage rahoge",
  "great customer service doesn't mean that the customere is always right, it means that the customer is always honoured.",
  "छाता बारिश नहीं रोक सकता परन्तु बारिश में खड़े रहने का हौसला अवश्य सफलता की गारन्टी तो नहीं देता, परन्तु सफलता के लिए संघर्ष करने की प्रेरणा अवश्य देता है।",
  "BETTER TO JUMP AND MAKE A MISTAKE THAN TO SIT THERE TOO FRIGHTENED TO MAKE A MOVE.",
  "Nothing is permanent in this world, not even our troubles.",
  "Some things have to end for better things to begin.",
  "i am imperfectly perfect in my perfectly imperfect world.",
  "Success has a thousand fathers but failure only belongs to the founders. -Sachin Bansal",
  "IF IT DOESN'T OPEN. IT'S NOT YOUR DOOR.",
  "WHEN YOU WANT TO GIVE UP REMEMBER, WHY YOU STARTED.",
  "A good life need some bad days.",
  "जो व्यक्ति खुदको Control कर सकता है वो जिंदगी में कुछ भी कर सकता है।",
  "Not everyone deserves to see all of your sides. -Shristy Sinha",
  "जिंदगी भी Science की तरह होती है, जितना Experiment करोगे उतना Better Result आएगा !!",
  "मेरी औकात तो मेरी माँ के कदमों के नीचे है",
  "Every next level of your life will demand a different you.",
  "Mind is nothing but traffic of thoughts. Select your route carefully.",
  "खुद को वक़्त दो क्योंकि आपकी पहली जरुरत आप खुद हो !!!",
  "time kharab chalata hai tab karta bura koi or hai or bhogata koi or hai",
  "Don't use your powers for evil",
  "negetiv logo se dur rahana ",
  "pahla banda to samaj seva karta hai or dusra banda dhanda banaata hai",
  "hamko hi had paar karni hai varna koi or kar dega",
  "jindgi me aapse har koi dur ho sakata hai par aapka kaam kabhi dur nahi hoga",
  "qualifire se milo to posittivity milegei",
  "aap ka kam apki brand hai",
  "jis chiz ki tarif hoti vhai repeat hoti hai",
  "1 degrees left airoplain concept land in pakistan",
  "jitni jyadad sangat postivity ki kroge to behatar rahega.",
  "sobhagyasali log khud apna babhisya likhte hai",
  "jo bhi sikhte hai use real life me apply karo",
  "jo sab kar rahe hai vo nahi karna hai kuch alag karna hai to mehnat bhi to alag kani padegi",
  "khujali aap ko hui hai to mitani bhi aap hi ko padegi kyoui vo sapna aapne chaha hai to pura bhi aapko bhi karna padega",
  "aise mat soch ki tu galti karete hue pakada gaya hai aise soch ki tu kuch bhi karle tujhe koi rok nahi sakta hai ",
  "jab do raaja aapas me ladte hai to sipahi to marte hi hai",
  "don't be a jack of all trades and Master of none that's too old don't just even be a master of one thing and done with it.",
  "You only have 3 seconds to make A good impression",
  "Don't judge a book by it's cover",
  "famous hone ke baad sab log aapki sunate hai",
  "vo ganagster hai to uska kaam hai khun karna to vo karega hi to tu apna kaam karna na",
  "हमें जो मिला है हमारे भाग्य से ज्यादा मिला है यदि आपके पांव में जूते नहीं है तो अफसोस मत कीजिए क्योंकि दुनिया में कई लोगो के पास पैर ही नहीं है",
  "आप केवल सोचते रह जाओगे और सब खत्म होता चला जाएगा समय कीमती है सुरुआत तो कीजिए",
  "कोशिश मालिक बनने की करो नौकर बनने की नहीं",
  "किसी को कमजोर मत समझो ₹5 का पेन भी 50000000 का चेक लिख सकता है",
  "कोई ऐसी मंजिल नहीं जहां तक पहुंचने का कोई रास्ता ना हो",
  "तस्वीरें लेना भी जरूरी है जिंदगी में साहब... आईने गुजरा हुआ वक्त नहीं बताया करते..",
  "काम करो नाम करो या फिर आराम करो खुदको बदनाम करो, मी तुम्हारी है!",
  "आपके पास कितने सारे हैं उससे कोई फर्क नहीं पड़ता। काम कितने आएंगे, वो महत्वपूर्ण है...",
  "इतना बेहतर भी न खोजो कि बेहतरीन ही खो दो।",
  "जीवन कठिन तब लगता है जब हम स्वयं में बदलाव करने की बजाय परिस्थितियों को बदलने का प्रयास करते हैं!",
  "कुछ लोग सरकारी बनना चाहते हैं और कुछ लोग सरकार बनना चाहते हैं",
  "क्यों रुक जाते हो चार दिन की मेहनत के बाद अरे वक्त लगता है बीज को फसल बनने में !",
  "মুर्ख को जवाब मत दो, ज्ञानी को ठुकराओ मत, अच्छे को जाने मत दो, बुरे को अपनाओ मत ",
  "आज अपने सपने औकात से बड़े देखो कल आपकी औकात आपके सपनों से बड़ी होगी",
  "दौलत तो विरासत में मिलती है लेकिन पहचान अपने दम पर बनानी पड़ती है।",
  "खुद को इतना कामयाब तो जरूर बनाएंगे छोड़ कर जाने वाले ,हमारी कामयाबी देखकर पछताएंगे।",
  "रेल की खिड़की पर बैठ के हर दफ़ा महसूस हुआ, जो जितना ज्यादा करीब था वो तेजी से दूर हुआ।",
  "चर्चाओं में रहने का शौक नहीं.. पर शख्सियत ही कुछ ऐसी है कि चर्चे चारो और है.!",
  "जंगल के उसूल वही जानता है जिनकी यारी शेरों के साथ होती है..!",
  "तुम हमें जानते हो और हम तुम्हें पहचानते है।",
  "हर वो आवाज दबानी है जिसने कहा था 'तुमसे ना हो पायेगा'",
  "फुर्सत में याद कर लेते थे वो हमें, और हम खुद को खास समझ बैठे!",
  "जब टाइम खर्च करना ही है तो अपने सपनों पर करो लोगों पर नहीं",
  "सफलता उन्हीं कामों को करने से मिलती है चीन काम को करने का मन नहीं करता",
  "उस जगह पर हमेशा खामोश रहना जहां दो कौड़ी के लोग अपनी हैसियत के गुण गाते हैं",
  "जिसका भी साथ दो खुलेआम दो विरोधी कहलाओगे गद्दार नहीं",
  "आपके माता-पिता हमेशा आपके साथ नहीं होंगे इसलिए बाबू सोना से अलग जाकर उनके बारे में सोचिए",
  "याद रखिए अगर आप किसी को अपना कीमती समय दोगे तो वह इंसान आपकी कदर कभी नहीं करेगा",
  "कोई भी कमजोर इंसान से प्यार नहीं करता लोग वहां जाना पसंद करते हैं जहां धन और यश पहले से मौजूद हो",
  "कभी भी किसी पर आंख बंद करके भरोसा मत करो क्योंकि दुनिया इतनी अच्छी नहीं है कि आपके भरोसे को कायम रखें",
  "काटने वाले जब चाटने लग जाए ना समझ लेना आप का टाइम चल रहा है",
  "बेटा बड़ा आदमी बनने के लिए सोच बड़ी रखनी पड़ती है",
  "जो चीज आप को चैलेंज करती है वही आपको चेंज करती है",
  "खुद को कमजोर समझना सबसे बड़ी भूल है",
  "शौक उनके अक्सर कम हो जाते हैं, जो कम उम्र में ही 'जिम्मेदार' हो जाते है..!!",
  "सत्य बहुत आसान होता है, लेकिन जब आप किसी को इसे समझाने लगते है तो यह बहुत कठिन हो जाता है ।",
  "No Matter How Precious You Are, If You Are Not In A Place That Values You, You Are Nothing!",
  "Life के हर movement को enjoy करो क्युकि ये जिंदगी है dear कोई movie नहीं जो रिटर्न लगाकर वापस आएगी।",
  "किसी को उजाड़ कर बसे, तो क्या बसे.? किसी को रुला कर हँसे, तो क्या हँसे.!?",
  "WHEN YOUR GOALS ARE MORE IMPORTANT THAN A PARTY, WELCOME TO THE 1% CLUB. WORK UNTIL YOU NO LONGER HAVE TO INTRODUCE YOURSELF",
  "Result aaye matak matak Papa mare patak patak Sanse jaye atak atak Ma ka dimag satak satak... Dil mera gothe khaye Kamar pe mere belt fly Body meri suji suji Khane mein jaise chappal khaye...",
  "कितना अच्छा होता अगर जीवन की सारी परेशानियाँ, स्टैटस जैसी होती 24 घंटे के बाद अपने आप डिलीट हो जाती !!",
  "Never forget the hands that raised you Words are Free, but we pay price only after using them..",
  "limited kamo se hi growth aati hai saare kamo se nahi",
  "कोई नही देगा तेरा साथ यहाँ तुझे लड़ना भी खुद है और संभलना भी खुद है.!",
  "Na mili Chandramukhi Na mili paaro Dekh ke girlfriend chutiyo ki Dil kehta hai ki, '/OHHH BHAI MAARO MUJHE MAARO/'",
  "Work hard until lamp light of your study table becomes a spot light of your Stage",
  "gunda aadmi gundai karna chahata hai krane do maja lena chahta hai maja lene do uske muh lagoge apne barabar bithaoge achha lagega vo vaidh tarika apna raha hai tum bhi vaidh tarika apno",
  "100 feet neeche paani hai to 99 feet khodakar chodane ka kya fayda ",
  "Sundar to tajmahal bhi hai lekin uski sundarataa barkarar rakhne ke liye kharch lagta hai",
  "जीवन भर खुश रहना है तो खुद को ऐसा बना लो की, कोई आपके साथ हो या ना हो आपको किसी चीज़ का गम नहीं होना चाहिए !!",
  "नाराज़ न होना कभी यह सोचकर की काम मेरा और नाम किसी का हो रहा है। घी और रुई सदियों से जलते चले आ रहे हैं और लोग कहते हैं दिया जल रहा है।",
  "देख बेटा ! पैसा कमाने के लिए मेहनत तो करनी पड़ेगी क्योंकि बेरोजगार का हाथ न तो पापा की परियां थामती है और न ही परिवार.. !",
  "अफवाह थी कि मेरी तबियत खराब है लोगों ने पूछ पूछकर बीमार के दिया",
  "सड़क अब तुम आई हो गांव जब सारा गांव शहर जा चुका है",
  "Mohabbat ho ya izzat, Kisi ko.. Itni mat do, Ki wo Tumhari kadar bhool jaaye..!",
  "बहाने बनाना छोड़ो काम करो। ● आलस आता है जल्दी सोया करो नॉलेज नहीं है - किताबें पढ़ो ● पेसा नहीं है कम खर्च और कमाना सीखो शरीर ठीक नहीं है. एक्सरसाइज़ किया करो ● टाइम नहीं है - फालतू काम मत करो",
  "अब मै सब कुछ छोड़कर तपस्या करने हिमालय पर जा रहा हूँ.. क्योंकि सुना है... तपस्वियों की तपस्या भंग करने अप्सरा आती है..",
  "जिसने पहला कदम उठा लिया है वो अंतिम भी उठा लेगा कठिनाई पहले में ही है अंतिम में नही है.!",
  "सुख और दुख अपने नसीब से मिलता है अमीरी-ग़रीबी से इसका कोई लेना देना नहीं ... रोने वाले महलों में भी रोते हैं और किस्मत में खुशियाँ हो तो झोपड़ी में भी हँसी गूंजती हैं !!",
  "जिस स्त्री का ध्यान मायके की तरफ़ ज्यादा हो, उस परिवार में महाभारत निश्चित है।",
  "हमेशा टूटने का मतलब खत्म नही होता, कभी कभी टूटने से जिंदगी की शुरुआत होती है...",
  "अगर कोई तुम्हारे लिए दरवाज़ा बन्द करे तो उसे अहसास दिला दो की कुंदी दोनों तरफ़ होती है।",
  "You know My Name, Not My Past. You've Heard What I've Done, Not What I've Been Through ",
  "Kuch बातें राज ही रहना बेहतर हैं ",
  "किसी चीज का अंत, एक नई शुरुआत का कारण होता हैं ",
  "जिंदगी में हमेशा PERMANENT कुछ भी नहीं होता ",
  "अच्छी चीजों के लिए वक्त लगता हैं ",
  "एक तरफ़ा रिश्तें पर मेहनत नहीं कि जाती ",
  "जो आपका हैं वो आपको मिलेगा ही ! ",
  "आखिर में सब चीजें रंग लाएंगी ",
  "उनकी तरह बने जिनके पास 72 लाख बैंक में और 3 लाख की कार हो ना की 72 लाख की कार पास हो और बैंक में सिर्फ 3 लाख ",
  "Get up otherwise Your Comfort zone Will kill You ",
  "जरूरी नहीं हर फील्ड में आप अच्छे हों ... लेकिन कोई तो ऐसा फील्ड होगा जिसमें आप सबके बाप हों !",
  "थोड़ा वक़्त लगेगा पर अपनी कहानी हम खुद लिखेंगे !",
  "ताश का जोकर और अपनों की ठोकर अक्सर बाजी घुमा देती है",
  "अपनी जन्दिगी को कुछ ऐसा बनाओ की आपके जीवन पर जो किताब लिखी जाये वो भी करोडो बना दे",
  "अकेले रहना सीखो, क्योंकि भीड, सहारा तो देती है मगर पहचान छीन लेती है",
  "सिर्फ एक विचार भी आपका जीवन बदल सकता है, बशर्ते आप उस पर संपूर्ण तौर पर अमल करने के लिए तैयार हो",
  "कुदरत का नियम है की अगली सीढ़ी पर चढ़ने के लिए पिछली सीढ़ी को छोड़ना पड़ता है, जबकि अधिकांश लोग अगली सीढ़ी पर चढ़ना तो चाहते है परंतु, पिछली सीढी को छोड़ना ही नहीं चाहते",
  "जन्दिगी एक खेल है, यह आप पर निर्भर करता है कि आप खिलाड़ी बनना चाहते हो या खिलौना",
  "सफलता के दोन नियम होते हैं : 1. कभी भी किसी को सारी चीजें मत बताना 2. नियम नंबर एक पढ़िए",
  "तरक्की और आराम कभी भी एक साथ नहीं रह सकते हैं",
  "जिंदगी में इतनी मेहनत करों की एक दिन तुम्हे तुम्हारी स्कूल में GUEST बनकर बुलाया जाए",
  "चारो तरफ पानी होने से जहाज नही डूबा करते, जहाज तब डूबता है जब पानी जहाज के अंदर आने लग जाये, आपके चारो तरफ जो हो रहा हैं उसे अंदर तक आने मत दे, अगर एकबार बाहर का माहौल आपके अंदर आने लग गया आप भी डूब जाएंगे।",
  "अपने ' शब्दों ' को सुंदर रखिए क्योंकि व्यक्ति चले जाते है परन्तु उनके कहे शब्द रह जाते हैं।",
  "तब मत रुको जब आप थक जाओ तब रुको जब आपका काम पूरा हो जाएं",
  "WORK HARD FOR YOUR DREAM BECAUSE SO MANY SEEKING THE SAME DREAM.",
  "Quitting is not in my genes",
  "ONE DAY THESE 5AM'S WILL MAKE YOU A LEGEND.",
  "जब ज़िंदगी जीने का तरीका भूल जाओ तो, पापा की तरफ मुड़ कर देख लेना !!.. ",
  "Black color Is Sentimentally Bad But, Every Black Board Makes The Students Life Bright.",
  "Man hona chahie kisi Ko yaad karne ka, waqt to apne aap hi mil jata hai",
  "घर तब तक नहीं टूटता जब तक फैसला बड़ों के हाथों में होता है, जब घर का हर कोई बड़ा बनने लगे, तो फिर घर टूटने में देर नहीं लगती  ",
  "जो हारता है वही तो जीतने का मतलब जाता है",
  "लोगों को जिस काम कि मना करे उसे ही लोग जनमूझ कर करते हैं पढाई की मना करो तो उसे हाथ भी नही लगाते हैं",
  "अगर में आमीर परिवार से नहीं हूँ तो क्या हुआ मेरा परिवार आमिर मेरी वजह से होगा",
  "झूठी शान के परिंदे ही ज्यादा फड़फड़ाते हैं, बाज़ की उड़ान में कभी आवाज नहीं होती...",
  "एक सपने के टूटकर चकनाचूर हो जाने के बाद दूसरा सपना देखने के हौसले को ज़िंदगी कहते हैं",
  "'दुनिया को लम्बे समय तक #मूर्ख नहीं बना सकते, लेकिन #धर्म एक ऐसा क्षेत्र है, जहां लोग  #पीढ़ी_दर_पीढ़ी मूर्ख बनते हैं।' - अब्राहम लिंकन; पूर्व अमेरिकी",
  "Nafart nahi hai Darsal interest hi nahi hai",
  "daal ko jaisa mod do vaise hi vo aage grow karega ",
  "If you don't prepare You will have to repair ",
  "किसी को घर से निकलते ही मिल गई मंजिल, कोई हमारी तरह उम्भर सफर में रहा।",
  "कुछ रिश्ते है, इसलिए चुप है.... कुछ चुप है, इसलिए रिश्ते है ! ",
  "don't wait kal enjoy har pal",
  "कभी भी अपने आप को सर्वोत्तम (घमंड) मत समझना",
  "नाम और पहचान भले ही छोटी हों, मगर खुद की होनी चाहिए",
  "किसी की मुस्कुराहट की वजह बनें या ना बनें, किसी के दर्द की वजह कभी ना बनें",
  "Jyada din Milne par hum comfort zone me chale jate hai",
  "Apne aap Ko uncomfortable rakho",
  "छोटे-छोटे बदलाव बड़ी कामयाबी दिलाते हैं, इसलिए आप अपने अंदर छोटे-छोटे बदलाव करिए निश्चिती ही आप एक दिन अपने अंदर एक बड़ा बदलाव देखेंगे।",
  "Knowledge not important Knowledge representation important",
  "Bhatti se bahar nikalte hi Koyal bujh jayega Isliye hamesha Bhati me hi rahana sekho ",
  "Kamyab hone ke liye akele hi aage badna padta hai",
  "Log to peeche tab aate hai jab hum kamyab hone lagte hai",
  "9 kari 1 na kari",
  "अगर बुरे लोग समझने से समझ तो बांसुरी बजाने वाला कभी महाभारत होने नहीं देता।",
  "Yesterday is history Tomorrow is mystery Today is gift  That's why it's called  'Present'",
  "GOD  G - Generator ( Brahma )  O - Ordinator  ( Vishnu )  D - Destroyer  ( Shiva)",
  "Kamyabi me full stop nahi hota Kamyabi me coma hote hote",
  "जिंदगी आप पर हंसती है, जब आप दुखी होते है, जिंदगी आप पर मुस्कराती है, जब आप खुश होते है, लेकिन, जिंदगी आपको सलाम करती है जब आप दूसरों को खुश करते है.....🙏",
  "कई जीत बाकी है कई हार बाकी है, अभी तो जिंदगी का सार बाकी है, 🙏 यहां से चले हैं नई मंजिल के लिए, यह तो पन्ना  था, अभी तो पूरी किताब बाकी है 🙏🙏🙏",
  "आदमी बड़ा हो या छोटा कोई फर्क नहीं पड़ता उसकी कहानी बड़ा होना चाहिए",
  "बेहतर व अच्छे  दिनों के लिए , बुरे दिनों से लड़ना पड़ता है Never give up✌✌",
  "कामयाब होने के लिए अपनी मेहनत पर विश्वास करना होता है, किस्मत तो जुए में अजमाई जाती है",
  "aapka beta jhut bol sakata hai aapka deta nahi",
  "agar aapko living banana hai to formal education se jaiye or yadi aapki fortune banana hai to self education par jaiye",
  "plain ladka udaye ya ladki plain ko koi fark nahi padata ki use kon uda raha hai to tumhe kyo fark padata hai barkudhhar",
  "baat bolegi to maar to padegi but nahi bolegi to zindagi bhar pachtayegi",
  "jo log mehanat ke saath nahi chodate kismat unka kabhi saath nahi chodati yaha bekar baithne se achha hai 2 hafte or mehnat kare vo kar sakta hai to tum kyo nahi",
  "middle class admi na ADAMI NAHI chutiya hota hai chutiya chahe bahnchod tum kitna bhi talant ho yahi paida hua yahi nipat jaoge",
  "tum kahe dekhoge munna mute hai to munna hi paani dalenge",
  "watch bilayti hai achha samay chal raha hai batate rahiye",
  "jab gunjais hogi tab dekh lenge zindagi nikal gai apki papa gunjais hi nahi hui",
  "middile clas vale dream bhi to dekh sakete hai dekhene paise thodi na lag rahe hai",
  "dusmni na aukat dekh kar ki jati hai ",
  "aap hamesa aag me haath dale hai to kavhi to jalega",
  "bahr konsa ukhad liye hai hm",
  "aurat ki khusi hamesa aadmi se upar hoti hai",
  "tum kahe chote mote gundo vala kaam karte ho",
  "faimily to saath me hi khana khati hai na",
  "sahar chalaoge to trigger khud nahi dabaoge uske liye aadmi chahiye",
  "aaj haminhe vafadar banayenge to vo hamare vafadar banenge.",
  "jab addmi ki ijjat na ho or use thodi ijjat do to vo 10 guna samman dete hai",
  "neta banaa hai na to gunde palo gunde bano nahi",
  "iski salah ki ham kadra karte hai par ye jaruri nahi ki ham mane",
  "bahar rahke bhi konsa bada ukhad liye hai hum dusre ka kaju kha rahe hai bhosadi vale",
  "bahut majboot niv dale hai tumhare liye sambhal ke nahi rakhoge to ghar gir jayega",
  "uski bahan ke saath kahe battamiji kiye veta ye chote mote gundo ka kaam hai hmko dekho ho kabhi kisi orat se battamiji se pes aate hue yad rakhna urat ki khusi hamesa aadmi se upar hoti hai",
  "family to saath me hi khana khati hai na ",
  "beta jab sahar chalago to trigger khud nahi dabaoge uske liye aadmi chahiye jo tumhare liye kaam karenge ",
  "aaj ham inhe vafadar banayenge to ye kal tumhare liye vafadar banenge maqbool ki tarah ",
  "thodi si ijjat diye hai jab to aadmi ko ijjat ki umeed na ho or use thodi si ijjat mil jaye to uski loylity 10 guna bad jati hai  or ye log family nahi bante sirf vafadar bante hai ",
  "munna bhaiya pyar se kah rahe hai to ud rahi ho utha lenge bich bajara me    ",
  "sanp ko chahe kitna bhi dudh pilado ek baar dusmni ho gai to vo dusman hi rahata hai or saap jitana bhi dusman ban jaye par rahta control sapere ke hi haath me hai hota bas alrt raho ",
  "jhut bolna bhi thik se sekh jao jhut vahi bolo jo samne vala pakad na paye ",
  "suno mamaji hm abhi inko join kiye hai or hamko chul mach rahi hmko bahut jayada hm tmhi se udghatna karenge ",
  "jiska marta hai vahi janata dard beta tha hmara ",
  "munna us khandan ki sabse kamjor kadi hai  aap sipahi ke piche lage hai lekin satarang rajja ko maar ke jite jati hai ",
  "aap bhi khech ligiye   tumhare paas hai hi kya jo khech le ",
  "kai saari hai jiski jitni aukat utne uske jariye ",
  "byapri bahut hai par cm ek hoti hai ",
  "resam heere ke jaisa hai supply control karne se hi daam control hota hai",
  "precaution achhi chiz hai lala",
  "are maqbool ijjat nahi karte hai darte haior dar hi yahi dikkat hai dar kabhi bhi kam ho sakata hai ",
  "sab chutiya com hoti hai baap ki ",
  "phir vahi baat tum saans lo or kas ke chodo",
  "kaam adhura nahi chodna chahiye tha ",
  "ho payega kahe nahi ho payega jarur ho payega ji",
  "ye pyar na badi chutiya chiz hai",
  "hm tumko achhe lagete ahi pat tum hamko ache nahi lagte",
  "gift hai gift ka rate thodi na puchate hai middle class valo ki tarah rate kahe puch rahi hai",
  "pahle se rai banake sochne se kya fayada didi ek ka sahi or dusre ka galat or ek ka galat dusare ka sahi bhi to ho skata hai didi ",
  "pahele yogy bano ",
  "thokne ke niyam hote hai jiske bare me jitna kam janoge thokna utna hi aasan hoga vrna ungliya trigger se hill jati hai ",
  "family family hoti hai family chahe kaise bhi ho family ke sath khada hona padta hai ",
  "ek to ghar me nai cheze aai hai or upar se aap   are cheze ghar me kitni bhi nai le aao roti to gehu ki hi khaoge na     ha khayenge na par roti ke sath dal ki jagah chicken to kha sakte hai na",
  "suru majboori me kiye the ab maja aa raha hai ",
  "are jo pahle nahi kar sakte the use ab kar sakte hai to use ab kahe nahi kar sakte usi ka naam tarrkki hai ",
  "janata ka saif hona jaruri nahi hai saif mahsoos karna jaruri hai",
  "sarso ko jitna mesoge to tel utna hi nikalega ",
  "chutiya hai ye important nahi hai hamara ladaka hai ye important hai ",
  "power jo hai netao ki tarah hoti hai rato rat badal sakti hai",
  "nai log politics me nahi aayenge to changes kaise hoga ",
  "ghar me koi bhi banda side line mahsoos nahi karna chahiye",
  "matter internal hai internally sulat jayega saap ghar me aake ke dosti karle rahata to zahrila hi hai ",
  "mudda ye hai ki tumne bina puche disison liya",
  "ketchuye dudh pikar sanp na ban jaye sambhal ke rakho ",
  "backup is important",
  "hm jante hai tum unke baap ho unke dusman mat bano",
  "bahut taklif hoti hai jab aap yogy ho or log aapki yogyata na pahchane bahut taklif hoti hai ",
  "family ki rai se chaloge to family ko or bhi proud hoga ",
  "jeet ki garanti tabhi hai jab jeet or haar dono tumhare control me ho",
  "ser ke muh ko khun laga chuka hai or vah bhukha bhi hai ser ko serni ka naram gost chahiye",
  "taklif unki nahi hoti jo chale jate hai taklif unki hoti hai jo peeche rah jate hai",
  "byapar hai bhaiya jiska mal uski beat or usi ka profit yahi patak ke chod denge chal nikal madrchod ",
  "bhosdike amar hai hm chutiya nahi hai to beta ye chutiyape ka kaam kahe kar rahe ho ",
  "kaise badaoge byapar ha badayenge imidiatly nahi soche hai ",
  "hm chutiya nahi bana rahe  aap chutiya hai ",
  "apno ke sukha dukha me samil na ho paye to kis kaam ki aise gaddi ",
  "aadmi ka darna jaruri hai marna jaruri nahi hai ",
  "kutte ke jaise bhauk rahe the   kutte ke malik ko dost bana lo kutta bhaukna band ho jayega",
  "kuch log bahubali paida hote hai or kuch ko bahubali banana padta hai",
  "hm to soche the ki sher is umar jyada hai lenkin buda nahi hua hai ",
  "kab se kaam kar rahi ho yaha , kitna payment milta hai yaha mirzapur aa jao double me kara denge ",
  "kya sekhe munna  yahi ki jab kurbani dene ka samaya aaye to kurbani sipahi ki di jati hai raja ki nahi raja to sirf raaj karne ke liye hota hai",
  "family hai aap log hamari ",
  "aadmi ke paas hamesa choice hoti hai par admi vahi chunta hai jo usko achha lagata hai ",
  "vo to nahi ho payega ",
  "vaise bhi sharma ji se kya sarmana  ",
  "aaj bhai log hi bahanchod ho gaye hai ",
  "chalo ye bhi thik hai ",
  "tulna usi se ki jati hai jo hamsse kamjor ho tabhi to hm better dikhenge ",
  "ye papa log na bahut control karte hai ",
  "ghayal janvar jyada khatrnak hota hai ",
  "dusman ko time par na mitaya jaye na to vahi dusman babasir bana jata hai",
  "karte nahi hai ho jata hai ",
  "dimag se operate karte karte dil ki bajah se maat kha gaye ",
  "khud ko age nahi karna chahiye tha ",
  "vafadari bahut kutti chiz hoti hai hm apni nibha rahe hai tum apni nibhao ",
  "rajniti me admi nahi fayada dekho ",
  "is sambhog ko sayog me badal do ",
  "rishte tabhi tak nibhate tab tak unhe todna mushkil ho ",
  "daru pine ke baad 6 mahine ka kaam 5 minutes me ho gaya",
  "juban or juji sab control me rahna chahiye ",
  "galat ko bhi sahi me convert karke har mauke ka fayada uthao ",
  "dukan band hai dhanda nahi ",
  "bhagwan krishn ke ke bhi kai saare rang the lekin vo prem ek hi karte the ",
  "logo ko ye na lage ki hm kmjor ho gaye hai ",
  "aurat ke pyar ya jal se bach ke raho varna barbad kar degi like bina   raja,mirzapur kalin ",
  "jarurat khatm rista khatm",
  "mirzapur mai hamre baap ek already hai jo hame bahut tite kiye hai to aap dusre banene ki kosis mat kijiye ",
  "jab javan beti ka samband kisi mard se ho jaye to saadi ho jana hi behtar rahta hai ",
  "beta vo cm hai neta kuch nahi deta hm bete vale hai to sara paisa apna hi kharch hoga ",
  "rajniti ka samman kursi se hota hai kursi gai power bhi gai ",
  "manjil par focus rakhiye raste ekhad baar haar jaye to kya fark padta hai ",
  "dil ki jagah dimag se sochiye",
  "free me kuch nahi milta ",
  "jangal ka niyam hai jo powerful hai vo dikhata bhi hai ",
  "goli hamesha naam dekhakar nahi lagti ",
  "kadava baat koi bhi bol sakata hai ",
  "kabhi kabhi insan bahut daba rahe to chot bhi bahut gahri deta hai ",
  "main aadmi ko pakad lo sabki gardan dab jati hai ",
  "baap kabhi bete ko marne ki nahi sochate hai ",
  "if you are entering in race by fault or fault you forgot all the things like first of all u win",
  "nanchana na jane to gane ko kharab nahi bolne ka",
  "lagta hai aaj mera mud nahi hai, mud, dusman tumhara mud nahi puchega jab maut samne hai ho to ladna hi padega chahe mud jo bhi ho",
  "dar dimag kamjor kar deta hai dar vo maut hai jo vismiti lati hai",
  "ye sirf vahi dekh rahe jo inhe dikhya ja raha hai",
  "agar aapko mera kaam acha lagta hai or us gore ko bhi mera kaam acha lagta hai to kyo na mai apne liye kaam karu",
  "ek baad yaad rakhana tum yaha kuch bhi karo kuch ankhe dekhati rahti hai or tum yaha kuch bhi kaho kuch kaan sunte rahte hai jo suna or dekha use batne ke kuch muh bhi hote hai dhyan rakhna ",
  "jaha achahi hoti hai vaha burai bhi hoti hai ",
  "service ko benaam rakhane ke liye tor networking ka istemal karte ho ",
  "koi chiz thik chal rahi to iska matlab ye nahi hai ki bo or thik nahi ho sakti ",
  "gunegaro ka to saath to bahut dete hai begunah ka saath hi kuch log dete hai to ham bhi apni had paar karte hai na ",
  "jai bhim   vakil ki  tarah pura jut jao us kaam me jab to final goal achieve na ho ",
  "एक 'माटी' का दिया सारी  रात अंधियारे से लड़ता है, तू तो 'भगवान' का दिया है तू किस किस बात से डरता है",
  "जब बेवज़ह कोई इल्ज़ाम लग जाए तो क्या कीजिये... हुज़ूर फिर यूँ कीजिये कि वो गुनाह कर लीजिए...!!",
  "जीवन में आपको रोकने टोकने वाला कोई है तो उनका अहसान मानिये क्योंकि जिन बागों में माली नहीं होते वो बाग़ जल्दी ही उजड़ जाते है।",
  "गंगा जी मे वही पाप धुलते है, जो गलती में हो जाए... योजना बना कर किए गए पाप, तो यमराज के लठ से ही धुलेंगे... ",
  "हमेशा हिम्मत रखो और आगे बढ़ो ताने तो भगवान को भी मिलते हैं तो आप तो एक इंसान हो !!",
  "जंजीर नहीं कटती तो अपने पांव काट लो, लंगड़ा कर चलो मगर आजादी से चलो।।",
  "दुनिया का सबसे कीमती तोहफा सच्चा हमसफ़र होता है.. जो पैसे से नहीं",
  "अच्छा वक़्त देखने के लिए, बुरे वक़्त से लड़ना पड़ता है !!",
  "अहंकार के वृक्ष पर विनाश का ही फल लगता है जय श्री राम",
  "ताकत आवाज़ में नहीं अपने विचारों में रखिए, क्योंकि फसल बारिश से होती है, बाढ़ से नहीं।",
  "छोटी -छोटी बातें दिल में रखने से बड़े -बड़े रिश्ते कमज़ोर हो जाते हैं",
  "परिवर्तन का रहस्य है कि आप अपनी सारी ऊर्जा पुराने से लड़ने में नहीं, बल्कि नए को बनाने में लगाएँ",
  "जो क्लास में बने मानीटर, कोरी शान दिखाते है ! आता जाता कुछ भी नहीं, पर हम पर रौब जमाते है जब क्लास में टीचर नहीं तो खुद टीचर बन जाते हैं कॉपी-पेंसिल लेकर बस नाम लिखने लग जाते हैं! खुद तो हमेशा बातें करे, हमें चुप करवाते हैं! अपनी तो बस गलती माफ़, हमें बलि चढ़ाते हैं! क्लास तो संभाल पाते नहीं, बस चीखते और चिल्लाते हैं! भगवान बचाएं इन मानीटर से, इन्हें हम नहीं चाहते हैं",
  "इंसान तब समझदार नही होता जब वो बड़ी बड़ी बातें करने लगता हैं, बल्कि वह तब समझदार होता हैं जब वो छोटी छोटी बाते समझने लगता हैं ।",
  "आपको जितना सोचना था सोच लिए अब तुरंत अभी के अभी अपना काम शुरू कीजिए. एक सफल व्यक्ति कभी अपना टाइम बर्बाद नहीं करता.",
  "हमेशा छोटी छोटी गलतियों से बचने की कोशिश किया करो, क्योंकि इन्सान पहाड़ो से नहीं पत्थरों से ठोकर खाता है..”",
  "वक्त बदलता सिर्फ उसी का है, जो वक्त को वक्त रहते समझ जाए",
  "कल से आप ऐसा क्या करने वाले हैं, जिससे आपकी जिंदगी में बदलाव आएगा-",
  "कभी भी लोगों की टीका टिप्पणी से घबराना नही चाहिए क्योंकि खेल में दर्शक ही शोर मचाते हैं खिलाड़ी नहीं",
  "किसी ने पूछा समाज को आगे बढ़ाने के लिए क्या करना चाहिए? एक विद्वान ने जवाब दिया टांग के बदले हाथ खींचो.!!",
  "मिलना है तो कदर करने वालो से मिलो। इस्तेमाल करने वाले तुम्हें खुद ही ढूंढ लेंगे।",
  "Is duniya me khusi tab milti hai jab hum anjan logo ki madad karte hai ",
  "जो आपके पास है, उसी से शुरूआत करो ;जहाँ पर हो वहीं से शुरूआत करो ;परफेक्ट मौके के इंतज़ार ने तो, न जाने कितने सपनो को बर्बाद कर दिया",
  "Aadami ki pahchan shakal se nahin kam se Hoti hai",
  "जिंदगी में एक बात हमेशा याद रखें कि बटर लगाने वाले के हाथ में हमेशा चाकू होता है!!",
  "जब भी चाहती है चुम लेती हैं माथा, माँ कभी तारीखों पर प्यार नहीं जताती!",
  "अपने बारे में...कभी गलत मत सोचो...क्योंकि... उसका ठेका तो दुनिया वालों ने ले रखा हैं.",
  "रात के उल्लू नहीं, सुबह की चहकती चिड़िया बनिए, मनोविशेषज्ञ सलाह देते हैं कि अपने मोबाइल को अलग कमरे में सुलाइए",
  "Silence is the best answer to someone who doesn't value your words.",
  "P.A.I.N.S Positive attitude In Negative Situations.",
  "It hurts like hell when someone makes you feel special, And then suddenly leaves you hanging and you have to act like you don't care",
  "किसी को मुफ़्त में मिल गया वो शख्श जो हमें हर कीमत में चाहिए था !",
  "'I want you back' Me talking to the money that I spent for nothing.",
  "'Never Beg' For a friendship or a relationship with anyone. If you don't receive the same efforts you give, Cut them off..",
  "Power is only need when you want to do something harmful, Otherwise love is enough to get everything done.",
  "प्रतिदिन सुप्रभात करने का यही एक आशय है कि... मुलाकात चाहे जब भी हो, अपनेपन का अहसास प्रतिदिन महसूस होता रहे!!",
  "Life is not about waiting for the storm to pass, it about learning to dance in rain",
  "Happiness is not a goal. It's a by product of a life well lived....",
  "शब्द भी एक भोजन है 'बोलने से पहले चख लीजिए' स्वयं को अगर अच्छा न लगे तो दूसरों को भी मत परोसिए",
  "i lost you. but i found me. so i win.",
  "Single! no problem. just earn money, travel, eat, drink and sleep.",
  "It will hurt, hurt and hurt but one day the pain and people both will leave",
  "बदलना होता है जिन्हे वो बदल जाते है, हर कोई जनवरी का इंतजार नहीं करता !!",
  "Don't Judge A Book By It's Cover",
  "सीखने पर फोकस करो पैसों पर फोकस करोगे तो वह लिमिट से आएगा लेकिन अगर सीखने पर फोकस करोगे तो अनलिमिटेड आएगा",
  `"तीन बेहतरीन सलाह
     1. सोचो मत, शुरुआत करो। 
     2. वादा मत करो, साबित करो। 
     3. बताओ मत, करके दिखाओ"`,
  `Power of Silence
     1. You can remain ahead of your competitors
     2. You wil achieve the state of ultra focus
     3. You will know yourself much better
     4. You will be safe from danger
     5. The first one to speak loses
     6. You will know other people's intentions `,
  'दौलत देखकर कभी रिश्ते मत बनाना क्योंकि साथ निभाने वाले अक्सर गरीब होते हैं',
  'अकेला रहना इस्तेमाल होने से बेहतर है',
  'जब किसी ने मुझे नजरअंदाज किया तो समझ आया अपनी हद में रहना कितना जरूरी है',
  'किसी को टच बढ़कर अगर तुम्हें अपनी श्रेष्ठता पर अभिमान हो तो यकीन मानो तुम नीति के सबसे ऊंची शिखर पर विराजमान हो',
  'मिला तो उनकी कृपा नहीं मिला तो उनकी इच्छा',
  'अकेले थे अच्छे थे लोग मिले तब उलझ सा गया',
  'कोई अगर आंख बंद करके भरोसा करें तो उसे यह एहसास मत दिलाना कि वह अंधा है',
  'वक्त के साथ बदल ही जाते हैं माधव अपने भी और सपने भी',
  'सुकून चाहिए तो कभी विवाह मत करना चैन की सांस चाहिए तो कभी भी प्रेम मत करना',
  'एक दिन बरसों का संघर्ष बहुत खूबसूरत तरीके से तुम्हें टकराएगा',
  'हमेशा सहते मत रहो मौका देखकर जवाब भी देना सीखो',
  'जिद करने की आदत अब सब्र में बदल गई है',
  'दुनिया को झूठे लोग की पसंद है सच कह दो तो अपने भी रूठ जाते हैं',
  'चतुराई चौपट करें ज्ञानी गोते खा भोले भाले लोगों को नारायण मिल जाए',
  'मुर्दों को भी हरी देता है कपड़ा लकड़ी आज जीवती न चिंता करें तक बड़ा भाग अभाग',
  'जब बात जरूर की हो तो जुबान सब की मीठी हो जाती है',
  'Best feeling taking your parents to amazing places',
  'Three things to know in life: Never trust anyone, Never beg anyone, Never depend on anyone.',
  'कर्मण्येवाधिकारस्ते — Focus on doing your best today; results will follow in time.',
  'अल्फाजों में कहां निकलती है असलियत दिल की महसूस जो होता है वह बताया नहीं जाता',
  'Dont be too humble, dont be too rude; just treat people according to their attitude.',
  'सफलता की हर सीढ़ी पर आपको एक कुत्ता जरूर मिलेगा। अगर हर कुत्ते से उलझोगे, तो मंजिल तक कभी नहीं पहुंच पाओगे।',
  'Silence is the best answer for all questions; smiling is the best reaction in every situation.',
  'अनुभव उमर से नहीं, परिस्थितियों से आता है। अच्छे वक्त से ज्यादा बुरा वक्त इंसान को बहुत कुछ सीखा जाता है।',
  'बात लगाओ और एहसास की होती है, वरना मैसेज तो कंपनी वाले भी करते हैं।',
  'कर्म करते रहो; लोग हाथ से छीन सकते हैं, नसीब से नहीं।',
  'प्रयास करेंगे, प्रभु की कोई अपराध न बने।',
  'जहां हर जगह बात समझनी पड़े, वहां शांत रहना ही बेहतर है।',
  'No matter how good you are, people will treat you according to their mood and needs.',
  'हर चीज का वक्त तय है, हर जगह तय है। आप कहीं पर पहुंचते नहीं, पहुंच जाते हो। खेल तुम नहीं, खेल तो वह रहा है।',
  'अपने मन में भी चल मत रखो, कपट मत रखो।',
  'वह संकट क्या मेरा बिगाड़ पाएगा, जब मेरे हनुमान को जान जाएगा।',
  'यकीन मानिए, प्रार्थनाएं सब कुछ बदल देती हैं।',
  'भगवान की दी हर परिस्थिति में कुछ ना कुछ सीख छुपी होती है।',
  'Think like a king, speak like a lawyer, dress like a mafia boss.',
  'विवाह करके 80 साल जिम्मेदारियां झेलने से अच्छा है, ख्वाब पूरे करके 50 साल में ही पंचतत्व में विलीन हो जाए।',
  'यह कभी मत मानो कि इसके पक्ष में बहुत से लोग हैं। वही सच्चा मनुष्य है, क्योंकि दुर्योधन के पक्ष में 90% लोग थे।',
  `रिश्ता अंत तक वही चलता है
  दोनों को खोने का डर हो,
  टाइम दिया जाता हो,
  ईगो की जगह समझने की आदत हो,
  किसी तीसरे की दखलअंदाजी ना हो।`,
  'Painful but true: If you over-love someone, you get overhead in return.',
  'सुविधाओं की कमी हो सकती है, मगर सुकून यही है।',
  'Maturity is when you realize people respect your success, not you.',
  'Build your character in such a way that even in a dark room, a girl feels safe with you.',
  'मन्नते पूरी हो ना हो, मैं दर नहीं बदलता।',
  'बदले से नहीं, बदलाव से मारो। उसे पछतावा नहीं, शर्म होनी चाहिए कि वह तुम्हारे जैसा दोस्त को चुका है।',
  'प्रेम हो या भोजन, किसी को ज्यादा दे दो तो वह अधूरा छोड़ कर चला जाता है।',
  'इंसान नहीं बोलता, उसके दिन बोलते हैं। और जब दिन सही ना हो, तो इंसान लाख बोले, कोई नहीं सुनता।',
  'If you cant work on the weekend in your 20s, you will be working a 9-to-5 all your 30s.',
  'I dont think about my personal life; I just think about winning.',
  'कोई पानी को तरस गया, किसी को मिला तो कदर ही नहीं की।',
  'इस संसार में अपना केवल समय है। अगर वह सही, तो सब अपने हैं।',
  'कल समय मिलेगा — यह कितना बड़ा भ्रम है।',
  'परमेश्वर के कदम बढ़ाने से पहले, विश्वास के कदम बढ़ाने जरूरी हैं। क्योंकि विश्वास वह चाबी है जो दरवाजे को खोलती है।',
  'मेरी औकात तो बस मेरी मां के कदमों में है।',
  'I accepted: जो आनंद शांत रहने में है, वह शिकायत करने में नहीं।',
  'दुनिया तुम्हें रहेगी तुम काबिल नहीं हो। तुम मुस्कुरा कर कहना — वक्त बताएगा।',
  'बर्ताव सबकी याद है; मुझे मुस्कुरा कर मिलने को माफी मत समझना।',
  'किस्मत ही तो रोती है, किस्मत बनाने वाला थोड़ी रूठा है।',
  'बेटे, वह कभी विकेट नहीं पाती जिन्होंने माता-पिता का संघर्ष देखा है।',
  'कम से ही महानता आती है; अच्छे कर्म से जीवन में धन्य हो जाता है।',
  'जो उम्मीद आपसे है ना माधव, वह किसी और से नहीं है।',
  'ईश्वर के जितने पास रहोगे, उतना खुश रहोगे।',
  'सिर्फ दिखावे के लिए अच्छे मत बनो; ईश्वर आपको बाहर से नहीं, अंदर से जानता है।',
  'जिसका इरादा हो साथ चलने का, वह बहाने नहीं, रास्ते ढूंढता है।',
  'मुंबई जैसी रोड नहीं, घाटी डरा देती है; भाई जैसा प्यार नहीं, भाभी लड़ा देती है।',
  'Efforts from both sides matter.',
  'सबसे बड़ी संपत्ति आपका दिमाग है; जैसा सोचोगे, वैसे बन जाओगे।',
  'बदलाव कष्ट देता है, लेकिन जरूरी है।',
  'कामयाब लड़का सबको स्वीकार है, लेकिन एक नाकामयाब बेटा सिर्फ मां स्वीकार करती है।',
  'रिश्तों को वक्त दिया जाता है, बहाने नहीं।',
  'अगर मैं नफरत के काबिल हूं, तो सोचिए मत, शौक से कीजिए।',
  'क्रोध के समय मौन और समस्या के समय मुस्कान — सबसे बड़ी ताकत होती है।',
  'मैं परफेक्ट नहीं हूं, लेकिन ऐसा इंसान भी नहीं हूं जो सिर्फ मतलब के लिए रिश्ता रखता है।',
  'उसका काम तुम्हें मिलना था, उसने मिलाया। संभालना तेरा, तू संभल नहीं पाया — गलती तेरी है।',
  'Life is not about love; sometimes we just need a person who understands us.',
  'हमसफर साथ देने वाला होना चाहिए; खूबसूरत ही का क्या है, वह तो वक्त आने पर बदल ही जाता है।',
  'Price is what you pay; value is what you get.',
  'दूरी ही अनादर का एकमात्र उत्तर है। प्रतिक्रिया न करें, बहस ना करें, नाटक में ना पड़े — बस अपनी उपस्थिति हटा दें।',
  'कुदरत के फैसले पर शक ना करना; अगर सजा मिल रही है, तो गुनाह भी हुआ होगा।',
  'काल: सत्यम बदती — समय आपको सत्य से अवगत करा ही देता है।',
  'Ego is not important in life what self-respect is most important in life.',
  'To establish permanent peace, it is necessary to break the peace.',
  'अच्छे कर्म करने से मिटते नहीं हैं भाग्य के लेख। तू अच्छे कर्म कर बंदे, फिर ईश्वर की महिमा देख।',
  'तारीफ करने वाला तुम्हारी स्थिति देखा है, और चिंता करने वाला तुम्हारी परिस्थिति देखा है।',
  'अपना किरदार ऐसा रखो कि तुम्हारा शांत रहना भी लोगों के दिलों में घाव कर दे।',
  'मोहब्बत सरेआम नहीं, बस एहसास होना चाहिए। हम उन्हें चाहते हैं — यह पता सिर्फ उन्हें होना चाहिए।',
  'हृदय जब एकांत चाहता है, तो बहुत कुछ त्यागना अनिवार्य हो जाता है।',
  'अपना सफर अकेले ही ठीक है; बेवजह उम्मीद रखना अच्छी बात नहीं है।',
  'Ideas are cheap; execution is everything.',
  'चुप रहने से आप लोगों की असली सच को पहचान पाते हो।',
  'सब कुछ नहीं मिलता जिंदगी में; कुछ चीज मुस्कुराते हुए छोड़ देना चाहिए।',
  'हे नारायण, अगर मैं कभी किसी के दुख का कारण बना हूं, तो कृपया उन्हें ठीक कर दीजिए और मुझे माफ कर दीजिए।',
  'तुम वहीं रहो जो तुम हो; फिर जो ठहर गया, वह तुम्हारा।',
  'सब सही हो रहा है; गलत इसलिए लग रहा है क्योंकि तुम्हारे हिसाब से नहीं हो रहा।',
  'दूसरों के देशों पर पीएचडी करने से बेहतर है कि हम खुद की मानसिकता पर केवल ग्रेजुएशन ही कर ले।',
  'दिल छोटा न कीजिए; जो बदल रहा है, उन्हें बदलने दीजिए।',
  'Living life with शिव संभालेंगे',
  'सम्मान सबका करो, मगर इज्जत उतनी ही करो जितनी आपको मिलती है।',
  'मां का दुख शरीर के दुख से भारी होता है।',
  'प्रभु अपना कार्य कर रहे हैं; क्या आप अपना कार्य कर रहे हो?',
  'कयामत खुद बताएगी, कयामत क्यों जरूरी है।',
  'ईश्वर की लिखी हर कहानी अलग है; उसका बनाया हर एक इंसान अलग है। So dont compare yourself to others just focus on yourself.',
  'जब स्वयं के निर्णय हर बार गलत सिद्ध हो, तो फिर मां-बाप के अनुसार चलना ही ठीक होता है।',
  'कल समय मिलेगा — यही कितना बड़ा भ्रम है।',
  'The current phase of life is बुरा लगता है तो लगने दो, मुझे भी लगा था।',
  'जब लाइफ ही टेंपरेरी है, तो कोई और परमानेंट कैसे होगा?',
  'हम भी गलत हैं किसी की कहानी में; कोई तो हमें भी रोज कोसता होगा।',
  'कर्म के पास ना तो कागज है, ना किताब है; फिर भी सारे जगत का हिसाब है।',
  'ज्ञान से खतरनाक कोई हथियार नहीं है; इसे फुल लोड करके रखें।',
  'जरूरत से ज्यादा प्रेम और ज्ञान मानसिक रोगी बना देता है।',
  'मृत्यु का कारण कोई रोग या दुर्घटना नहीं, बल्कि जन्म है।',
  'पल-पल रंग बदल रही है यह दुनिया, और लोग पूछ रहे हैं कि होली कब है?',
  'Small circle, private life, clear mind, happy heart.',
  'क्यों ना अभी बेफिक्र सोया जाए; अब बचा ही क्या है जिसे खाया जाए?',
  'खुश रहना सस्ता है, और कुछ दिखाना महंगा।',
  'दिल छोटा न कीजिए; जो बदल रहा है, उन्हें बदलने दीजिए।',
  'अलग होना आपकी ताकत है, कमजोरी नहीं; इसीलिए अलग होने से मत डरो।',
  'जिंदगी वही है जो जी रहे हैं; यह करेंगे, वह करेंगे तो बस ख्वाब है।',
  'Stop thinking negative things because your thoughts can harm your present time.',
  'रिटर्न टिकट कंफर्म है; हम सबका कैंसिल कोई कर नहीं सकता। इसलिए यात्रा का पूरा आनंद लें।',
  'जाने दो सबको; तुम्हारे पास तो श्री कृष्ण है।',
  'घाव ठीक हो जाने से, घाव देने वालों को भुलाया नहीं जा सकता।',
  'गैरों की बात सुनकर अपनों से उलझा नहीं करते।',
  'सबसे बड़ा पाप है — खुद को कमजोर समझना। The biggest sin is to consider yourself weak.',
  'Being a woman is a challenging journey, but your strength knows no bounds.',
  'लोग समय मांगने को तरसेंगे; तुम खुद पर समय लगाओ तो सही।',
  'भारतीय समाज ऐसा है जहां उधार दिए हुए पैसे वापस मांगने पर बताना पड़ता है कि मुझे पैसे किस काम के लिए चाहिए।',
  'लोगों की तरह दिखावा नहीं करता हूं; अच्छा-बुरा जैसा भी, ओरिजिनल हूं।',
  'एक युद्ध करो अपने आप से, और त्याग दो सारी बुरी आदतें।',
  'सबसे बड़ी संपत्ति आपका दिमाग है; जैसा सोचोगे, वैसा बन जाओगे।',
  'तू भागीरथी सी चंचल, में अलकनंदा सा शांतिप्रिय; जब संगम हो हमारा, तू बन गंगा और मैं तेरा घाट प्रिया।',
  'अपनी मन की किताब ऐसे इंसान के आगे खोलें जो पढ़ने के साथ-साथ समझ भी सके।',
];
